<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="14" passed="13">
  <reporter-output>
  </reporter-output>
  <suite name="Automation Project Test Suite" duration-ms="36" started-at="2013-08-08T11:54:52Z" finished-at="2013-08-08T11:54:52Z">
    <groups>
      <group name="initQAEnv">
        <method signature="InitializationTests_TestSet.isQAEnvOK()[pri:0, instance:com.organization.automation.project.spice.mix.testng.feature.abstract_tc.tests.InitializationTests_TestSet@1108c18]" name="isQAEnvOK" class="com.organization.automation.project.spice.mix.testng.feature.abstract_tc.tests.InitializationTests_TestSet"/>
      </group> <!-- initQAEnv -->
      <group name="Abstract.TC.basic">
        <method signature="AcceptanceTests_Feature_AbstractTC.isAbstractTCworks(com.organization.automation.project.spice.mix.testng.test.AbstractTestCase)[pri:0, instance:com.organization.automation.project.spice.mix.testng.feature.abstract_tc.tests.AcceptanceTests_Feature_AbstractTC@450fe6]" name="isAbstractTCworks" class="com.organization.automation.project.spice.mix.testng.feature.abstract_tc.tests.AcceptanceTests_Feature_AbstractTC"/>
      </group> <!-- Abstract.TC.basic -->
      <group name="initLocalEnv">
        <method signature="InitializationTests_TestSet.isLocalTAFEnvOK()[pri:0, instance:com.organization.automation.project.spice.mix.testng.feature.abstract_tc.tests.InitializationTests_TestSet@1108c18]" name="isLocalTAFEnvOK" class="com.organization.automation.project.spice.mix.testng.feature.abstract_tc.tests.InitializationTests_TestSet"/>
      </group> <!-- initLocalEnv -->
      <group name="CustomAssertTests">
        <method signature="CustomAssertUnitTests.testBigIntegerAssert_bigNumbersCase()[pri:0, instance:com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests@15b0184]" name="testBigIntegerAssert_bigNumbersCase" class="com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests"/>
        <method signature="CustomAssertUnitTests.testBigIntegerAssert_bigNumbersEqualObjectCase()[pri:0, instance:com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests@15b0184]" name="testBigIntegerAssert_bigNumbersEqualObjectCase" class="com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests"/>
        <method signature="CustomAssertUnitTests.testBigIntegerAssert_bigNumbersLessCase()[pri:0, instance:com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests@15b0184]" name="testBigIntegerAssert_bigNumbersLessCase" class="com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests"/>
        <method signature="CustomAssertUnitTests.testBigIntegerAssert_bigNumbersMoreCase()[pri:0, instance:com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests@15b0184]" name="testBigIntegerAssert_bigNumbersMoreCase" class="com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests"/>
        <method signature="CustomAssertUnitTests.testBigIntegerAssert_mixNumbersLessCase()[pri:0, instance:com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests@15b0184]" name="testBigIntegerAssert_mixNumbersLessCase" class="com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests"/>
        <method signature="CustomAssertUnitTests.testBigIntegerAssert_mixNumbersMoreCase()[pri:0, instance:com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests@15b0184]" name="testBigIntegerAssert_mixNumbersMoreCase" class="com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests"/>
        <method signature="CustomAssertUnitTests.testBigIntegerAssert_smallNumbersCase()[pri:0, instance:com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests@15b0184]" name="testBigIntegerAssert_smallNumbersCase" class="com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests"/>
        <method signature="CustomAssertUnitTests.testBigIntegerAssert_smallNumbersFailCase()[pri:0, instance:com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests@15b0184]" name="testBigIntegerAssert_smallNumbersFailCase" class="com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests"/>
        <method signature="CustomAssertUnitTests.testBigIntegerAssert_smallNumbersLessCase()[pri:0, instance:com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests@15b0184]" name="testBigIntegerAssert_smallNumbersLessCase" class="com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests"/>
        <method signature="CustomAssertUnitTests.testBigIntegerAssert_smallNumbersMoreCase()[pri:0, instance:com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests@15b0184]" name="testBigIntegerAssert_smallNumbersMoreCase" class="com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests"/>
        <method signature="CustomAssertUnitTests.testBigIntegerAssert_smallNumbersNegativeCase()[pri:0, instance:com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests@15b0184]" name="testBigIntegerAssert_smallNumbersNegativeCase" class="com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests"/>
      </group> <!-- CustomAssertTests -->
      <group name="AbstractTCs">
        <method signature="AcceptanceTests_Feature_AbstractTC.isAbstractTCworks(com.organization.automation.project.spice.mix.testng.test.AbstractTestCase)[pri:0, instance:com.organization.automation.project.spice.mix.testng.feature.abstract_tc.tests.AcceptanceTests_Feature_AbstractTC@450fe6]" name="isAbstractTCworks" class="com.organization.automation.project.spice.mix.testng.feature.abstract_tc.tests.AcceptanceTests_Feature_AbstractTC"/>
      </group> <!-- AbstractTCs -->
      <group name="InitializationTests">
        <method signature="InitializationTests_TestSet.isLocalTAFEnvOK()[pri:0, instance:com.organization.automation.project.spice.mix.testng.feature.abstract_tc.tests.InitializationTests_TestSet@1108c18]" name="isLocalTAFEnvOK" class="com.organization.automation.project.spice.mix.testng.feature.abstract_tc.tests.InitializationTests_TestSet"/>
        <method signature="InitializationTests_TestSet.isQAEnvOK()[pri:0, instance:com.organization.automation.project.spice.mix.testng.feature.abstract_tc.tests.InitializationTests_TestSet@1108c18]" name="isQAEnvOK" class="com.organization.automation.project.spice.mix.testng.feature.abstract_tc.tests.InitializationTests_TestSet"/>
      </group> <!-- InitializationTests -->
    </groups>
    <test name="AcceptanceTests" duration-ms="36" started-at="2013-08-08T11:54:52Z" finished-at="2013-08-08T11:54:52Z">
      <class name="com.organization.automation.project.spice.mix.testng.feature.abstract_tc.tests.AcceptanceTests_Feature_AbstractTC">
        <test-method status="PASS" signature="setUpSet()[pri:0, instance:com.organization.automation.project.spice.mix.testng.feature.abstract_tc.tests.AcceptanceTests_Feature_AbstractTC@450fe6]" name="setUpSet" is-config="true" duration-ms="0" started-at="2013-08-08T14:54:52Z" finished-at="2013-08-08T14:54:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpSet -->
        <test-method status="PASS" signature="setUpTest()[pri:0, instance:com.organization.automation.project.spice.mix.testng.feature.abstract_tc.tests.AcceptanceTests_Feature_AbstractTC@450fe6]" name="setUpTest" is-config="true" duration-ms="1" started-at="2013-08-08T14:54:52Z" finished-at="2013-08-08T14:54:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpTest -->
        <test-method status="PASS" signature="isAbstractTCworks(com.organization.automation.project.spice.mix.testng.test.AbstractTestCase)[pri:0, instance:com.organization.automation.project.spice.mix.testng.feature.abstract_tc.tests.AcceptanceTests_Feature_AbstractTC@450fe6]" name="isAbstractTCworks" duration-ms="5" depends-on-groups="InitializationTests" started-at="2013-08-08T14:54:52Z" data-provider="Abstract.TC" finished-at="2013-08-08T14:54:52Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.organization.automation.project.spice.mix.testng.test.AbstractTestCase@b6507e]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- isAbstractTCworks -->
        <test-method status="PASS" signature="tearDownTest()[pri:0, instance:com.organization.automation.project.spice.mix.testng.feature.abstract_tc.tests.AcceptanceTests_Feature_AbstractTC@450fe6]" name="tearDownTest" is-config="true" duration-ms="0" started-at="2013-08-08T14:54:52Z" finished-at="2013-08-08T14:54:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownTest -->
        <test-method status="PASS" signature="tearDownSet()[pri:0, instance:com.organization.automation.project.spice.mix.testng.feature.abstract_tc.tests.AcceptanceTests_Feature_AbstractTC@450fe6]" name="tearDownSet" is-config="true" duration-ms="0" started-at="2013-08-08T14:54:52Z" finished-at="2013-08-08T14:54:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownSet -->
      </class> <!-- com.organization.automation.project.spice.mix.testng.feature.abstract_tc.tests.AcceptanceTests_Feature_AbstractTC -->
      <class name="com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests">
        <test-method status="PASS" signature="setUpAllTests(java.lang.String)[pri:0, instance:com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests@15b0184]" name="setUpAllTests" is-config="true" duration-ms="0" started-at="2013-08-08T14:54:52Z" finished-at="2013-08-08T14:54:52Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Unit Tests on Custom Assert]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpAllTests -->
        <test-method status="PASS" signature="testBigIntegerAssert_bigNumbersCase()[pri:0, instance:com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests@15b0184]" name="testBigIntegerAssert_bigNumbersCase" duration-ms="5" started-at="2013-08-08T14:54:52Z" finished-at="2013-08-08T14:54:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testBigIntegerAssert_bigNumbersCase -->
        <test-method status="PASS" signature="testBigIntegerAssert_bigNumbersEqualObjectCase()[pri:0, instance:com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests@15b0184]" name="testBigIntegerAssert_bigNumbersEqualObjectCase" duration-ms="1" started-at="2013-08-08T14:54:52Z" finished-at="2013-08-08T14:54:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testBigIntegerAssert_bigNumbersEqualObjectCase -->
        <test-method status="PASS" signature="testBigIntegerAssert_bigNumbersLessCase()[pri:0, instance:com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests@15b0184]" name="testBigIntegerAssert_bigNumbersLessCase" duration-ms="0" started-at="2013-08-08T14:54:52Z" finished-at="2013-08-08T14:54:52Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Actual number should be equal expected. expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Actual number should be equal expected. expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssert.assertEquals(CustomAssert.java:39)
	at com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests.testBigIntegerAssert_bigNumbersLessCase(CustomAssertUnitTests.java:115)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testBigIntegerAssert_bigNumbersLessCase -->
        <test-method status="PASS" signature="testBigIntegerAssert_bigNumbersMoreCase()[pri:0, instance:com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests@15b0184]" name="testBigIntegerAssert_bigNumbersMoreCase" duration-ms="1" started-at="2013-08-08T14:54:52Z" finished-at="2013-08-08T14:54:52Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Actual number should be equal expected. expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Actual number should be equal expected. expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssert.assertEquals(CustomAssert.java:39)
	at com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests.testBigIntegerAssert_bigNumbersMoreCase(CustomAssertUnitTests.java:107)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testBigIntegerAssert_bigNumbersMoreCase -->
        <test-method status="PASS" signature="testBigIntegerAssert_mixNumbersLessCase()[pri:0, instance:com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests@15b0184]" name="testBigIntegerAssert_mixNumbersLessCase" duration-ms="1" started-at="2013-08-08T14:54:52Z" finished-at="2013-08-08T14:54:52Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Actual number should be equal expected. expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Actual number should be equal expected. expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssert.assertEquals(CustomAssert.java:39)
	at com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests.testBigIntegerAssert_mixNumbersLessCase(CustomAssertUnitTests.java:131)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testBigIntegerAssert_mixNumbersLessCase -->
        <test-method status="PASS" signature="testBigIntegerAssert_mixNumbersMoreCase()[pri:0, instance:com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests@15b0184]" name="testBigIntegerAssert_mixNumbersMoreCase" duration-ms="0" started-at="2013-08-08T14:54:52Z" finished-at="2013-08-08T14:54:52Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Actual number should be equal expected. expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Actual number should be equal expected. expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssert.assertEquals(CustomAssert.java:39)
	at com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests.testBigIntegerAssert_mixNumbersMoreCase(CustomAssertUnitTests.java:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testBigIntegerAssert_mixNumbersMoreCase -->
        <test-method status="PASS" signature="testBigIntegerAssert_smallNumbersCase()[pri:0, instance:com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests@15b0184]" name="testBigIntegerAssert_smallNumbersCase" duration-ms="0" started-at="2013-08-08T14:54:52Z" finished-at="2013-08-08T14:54:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testBigIntegerAssert_smallNumbersCase -->
        <test-method status="FAIL" signature="testBigIntegerAssert_smallNumbersFailCase()[pri:0, instance:com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests@15b0184]" name="testBigIntegerAssert_smallNumbersFailCase" duration-ms="0" started-at="2013-08-08T14:54:52Z" finished-at="2013-08-08T14:54:52Z">
          <exception class="org.testng.TestException">
            <message>
              <![CDATA[
Expected exception java.lang.AssertionError but got org.testng.TestException: 
Expected exception java.lang.AssertionError but got java.lang.ArithmeticException: / by zero]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestException: 
Expected exception java.lang.AssertionError but got org.testng.TestException: 
Expected exception java.lang.AssertionError but got java.lang.ArithmeticException: / by zero
	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1497)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1245)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: org.testng.TestException: 
Expected exception java.lang.AssertionError but got java.lang.ArithmeticException: / by zero
	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1497)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:754)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	... 16 more
Caused by: java.lang.ArithmeticException: / by zero
	at com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests.testBigIntegerAssert_smallNumbersFailCase(CustomAssertUnitTests.java:89)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testBigIntegerAssert_smallNumbersFailCase -->
        <test-method status="PASS" signature="testBigIntegerAssert_smallNumbersLessCase()[pri:0, instance:com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests@15b0184]" name="testBigIntegerAssert_smallNumbersLessCase" duration-ms="0" started-at="2013-08-08T14:54:52Z" finished-at="2013-08-08T14:54:52Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Actual number should be equal expected. expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Actual number should be equal expected. expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssert.assertEquals(CustomAssert.java:39)
	at com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests.testBigIntegerAssert_smallNumbersLessCase(CustomAssertUnitTests.java:99)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testBigIntegerAssert_smallNumbersLessCase -->
        <test-method status="PASS" signature="testBigIntegerAssert_smallNumbersMoreCase()[pri:0, instance:com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests@15b0184]" name="testBigIntegerAssert_smallNumbersMoreCase" duration-ms="0" started-at="2013-08-08T14:54:52Z" finished-at="2013-08-08T14:54:52Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Actual number should be equal expected. expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Actual number should be equal expected. expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssert.assertEquals(CustomAssert.java:39)
	at com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests.testBigIntegerAssert_smallNumbersMoreCase(CustomAssertUnitTests.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testBigIntegerAssert_smallNumbersMoreCase -->
        <test-method status="PASS" signature="testBigIntegerAssert_smallNumbersNegativeCase()[pri:0, instance:com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests@15b0184]" name="testBigIntegerAssert_smallNumbersNegativeCase" duration-ms="0" started-at="2013-08-08T14:54:52Z" finished-at="2013-08-08T14:54:52Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Actual number should be equal expected. expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Actual number should be equal expected. expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssert.assertEquals(CustomAssert.java:39)
	at com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests.testBigIntegerAssert_smallNumbersNegativeCase(CustomAssertUnitTests.java:139)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testBigIntegerAssert_smallNumbersNegativeCase -->
      </class> <!-- com.organization.automation.project.spice.mix.testng.extension.assertions.CustomAssertUnitTests -->
      <class name="com.organization.automation.project.spice.mix.testng.feature.abstract_tc.tests.InitializationTests_TestSet">
        <test-method status="PASS" signature="setUpSuite(java.lang.String)[pri:0, instance:com.organization.automation.project.spice.mix.testng.feature.abstract_tc.tests.InitializationTests_TestSet@1108c18]" name="setUpSuite" is-config="true" duration-ms="4" started-at="2013-08-08T14:54:52Z" finished-at="2013-08-08T14:54:52Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Automation Project]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpSuite -->
        <test-method status="PASS" signature="setUpSet(java.lang.String)[pri:0, instance:com.organization.automation.project.spice.mix.testng.feature.abstract_tc.tests.InitializationTests_TestSet@1108c18]" name="setUpSet" is-config="true" duration-ms="0" started-at="2013-08-08T14:54:52Z" finished-at="2013-08-08T14:54:52Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Initialization Tests]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpSet -->
        <test-method status="PASS" signature="setUpTest()[pri:0, instance:com.organization.automation.project.spice.mix.testng.feature.abstract_tc.tests.InitializationTests_TestSet@1108c18]" name="setUpTest" is-config="true" duration-ms="1" started-at="2013-08-08T14:54:52Z" finished-at="2013-08-08T14:54:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpTest -->
        <test-method status="PASS" signature="tearDownTest()[pri:0, instance:com.organization.automation.project.spice.mix.testng.feature.abstract_tc.tests.InitializationTests_TestSet@1108c18]" name="tearDownTest" is-config="true" duration-ms="1" started-at="2013-08-08T14:54:52Z" finished-at="2013-08-08T14:54:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownTest -->
        <test-method status="PASS" signature="isLocalTAFEnvOK()[pri:0, instance:com.organization.automation.project.spice.mix.testng.feature.abstract_tc.tests.InitializationTests_TestSet@1108c18]" name="isLocalTAFEnvOK" duration-ms="0" started-at="2013-08-08T14:54:52Z" finished-at="2013-08-08T14:54:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- isLocalTAFEnvOK -->
        <test-method status="PASS" signature="isQAEnvOK()[pri:0, instance:com.organization.automation.project.spice.mix.testng.feature.abstract_tc.tests.InitializationTests_TestSet@1108c18]" name="isQAEnvOK" duration-ms="1" depends-on-groups="initLocalEnv" started-at="2013-08-08T14:54:52Z" finished-at="2013-08-08T14:54:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- isQAEnvOK -->
        <test-method status="PASS" signature="setUpTest()[pri:0, instance:com.organization.automation.project.spice.mix.testng.feature.abstract_tc.tests.InitializationTests_TestSet@1108c18]" name="setUpTest" is-config="true" duration-ms="0" started-at="2013-08-08T14:54:52Z" finished-at="2013-08-08T14:54:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpTest -->
        <test-method status="PASS" signature="tearDownTest()[pri:0, instance:com.organization.automation.project.spice.mix.testng.feature.abstract_tc.tests.InitializationTests_TestSet@1108c18]" name="tearDownTest" is-config="true" duration-ms="0" started-at="2013-08-08T14:54:52Z" finished-at="2013-08-08T14:54:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownTest -->
        <test-method status="PASS" signature="tearDownSet()[pri:0, instance:com.organization.automation.project.spice.mix.testng.feature.abstract_tc.tests.InitializationTests_TestSet@1108c18]" name="tearDownSet" is-config="true" duration-ms="1" started-at="2013-08-08T14:54:52Z" finished-at="2013-08-08T14:54:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownSet -->
        <test-method status="PASS" signature="tearDownSuite()[pri:0, instance:com.organization.automation.project.spice.mix.testng.feature.abstract_tc.tests.InitializationTests_TestSet@1108c18]" name="tearDownSuite" is-config="true" duration-ms="0" started-at="2013-08-08T14:54:52Z" finished-at="2013-08-08T14:54:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownSuite -->
      </class> <!-- com.organization.automation.project.spice.mix.testng.feature.abstract_tc.tests.InitializationTests_TestSet -->
    </test> <!-- AcceptanceTests -->
  </suite> <!-- Automation Project Test Suite -->
</testng-results>
